cmangos/tbc-db

- InstallFullDB.sh
Just added the possibility to change database server port on the database installation script.
> Added DB_PORT config

- Updates/692_Fix_Incorrect_Plan_Drop.sql
- Updates/824_Complete_Karazhan_Development.sql
a few more fixes for table names
> fix capitalization issues

- InstallFullDB.sh
related: https://github.com/cmangos/classic-db/pull/149
> Update InstallFullDB.sh: remove WAIT var, writing FORCE_WAIT to the config

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=22342/deathshadow-spellbinder
https://web.archive.org/web/20110625084603/http://www.wowhead.com:80/npc=22342
> [ACID] Correct Spellid for c.22342

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=16967/haaleshi-talonguard
https://web.archive.org/web/20110629234909/http://www.wowhead.com:80/npc=16967
> [ACID] Haaleshi Talonguard 16967

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21189/crystal-flayer
> [ACID] Crystal Flayer 21189 NSR

- ACID/acid_tbc.sql
-145 was already used so there must be some sync issue there.
> Fix Text -143 - -145 and add corresponding AIs

- Updates/595_damageschools.sql
- Updates/xxx_c23192_damageschool.sql
http://www.wowhead.com/npc=23192/ember-of-azzinoth
> Adjust Damageschool for Ember of Azzinoth 23192

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21273/phaseshift-bulwark
http://wowwiki.wikia.com/wiki/Phaseshift_Bulwark?oldid=1628493
http://wowwiki.wikia.com/wiki/Kael%27thas_Sunstrider_(tactics)?oldid=1622799
> [ACID] Phaseshift Bulwark 21273

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21274/staff-of-disintegration
http://wowwiki.wikia.com/wiki/Staff_of_Disintegration?oldid=1546309
http://wowwiki.wikia.com/wiki/Kael%27thas_Sunstrider_(tactics)?oldid=1622799
* It likes to cast a Frost Nova, run away 10-15 yards and then start to Frostbolt.
> [ACID] Staff of Disintegration 21274

- ACID/acid_tbc.sql
- Updates/851_c18521_aura.sql
- Updates/xxx_c18521_aura.sql
http://www.wowhead.com/npc=18521/raging-skeleton
> [ACID] Raging Skeleton 18521

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21787/time-lost-skettis-high-priest
> [ACID] Time-Lost Skettis High Priest 21787

- ACID/acid_tbc.sql
- Updates/503_outland_auras.sql
http://www.wowhead.com/npc=22044/cavern-crawler
> [ACID] Cavern Crawler 22044

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23008/ethereum-jailor
https://web.archive.org/web/20110805233626/http://www.wowhead.com:80/npc=23008
* Maybe some additional aura for the red colorchange, couldnt find it in sniff but it has to be there, maybe some model change.
> [ACID] Ethereum Jailor 23008

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21986/altar-of-shatar-vindicator
> [ACID] Altar of Shatar Vindicator 21986

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=22452/reanimated-exarch
https://web.archive.org/web/20111122085341/http://www.wowhead.com:80/npc=22452
* Might also use 33910 and 36004
* probably should have nontargetableflag by default and removed on timer ooc to make it more rp like
> [ACID] Reanimated Exarch 22452

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=22862/anchorite-caalen
> [ACID] Anchorite Caalen 22862

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=22863/seasoned-magister
> [ACID] Seasoned Magister 22863

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21448/gadgetzan-sniper
> [ACID] Gadgetzan Sniper 21448 s.12024

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=18113/feralfen-hunter
> [ACID] Feralfen Hunter 18113 s.12024

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=20435/overseer-athanel
> [ACID] Overseer Anthanel 20435

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=19996/bladespire-battlemage
https://web.archive.org/web/20111031113633/http://www.wowhead.com:80/npc=19996
> [ACID] Bladespire Battlemage 19996

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=19997/bladespire-enforcer
https://web.archive.org/web/20111031110938/http://www.wowhead.com:80/npc=19997
> [ACID] Bladespire Enforcer 19997

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=20753/dorgok
https://web.archive.org/web/20110630205338/http://www.wowhead.com:80/npc=20753#abilities
> [ACID] Dorgok 20753

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=20756/bladespire-chef
https://web.archive.org/web/20120111025114/http://www.wowhead.com:80/npc=20756#abilities
> [ACID] Bladespire Chef 20756

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21238/bloodmaul-drudger
https://web.archive.org/web/20150424035131/http://www.wowhead.com/npc=21238/bloodmaul-drudger
> [ACID] Bloodmaul Drudger 21238

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=21975/bladespire-sober-defender
https://web.archive.org/web/20120228052309/http://www.wowhead.com:80/npc=21975
> [ACID] Bladespire Sober Defender 21975

- ACID/acid_tbc.sql
- Updates/912_remove_static_spawn.sql
http://www.wowhead.com/npc=675/venture-co-foreman
https://web.archive.org/web/20120120140314/http://www.wowhead.com:80/npc=675
```675 ooc movement script with: "Work you dogs! Put your back into it!"```
http://www.wowhead.com/npc=676/venture-co-surveyor#comments
https://web.archive.org/web/20120221195356/http://www.wowhead.com:80/npc=676
http://www.wowhead.com/spell=7979/compact-harvest-reaper
https://web.archive.org/web/20111120225117/http://www.wowhead.com:80/npc=2676
http://www.wowhead.com/npc=2676/compact-harvest-reaper#comments
http://www.wowhead.com/npc=677/venture-co-tinkerer
https://web.archive.org/web/20110705032238/http://www.wowhead.com:80/npc=677
> [ACID] Venture Co. - Foreman 675 & Surveyor 676 & Tinkerer 677

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=20888/solus-the-eternal
36778	17467	36786	9613
> [ACID] Solus the Eternal 20888

- ACID/acid_tbc.sql
- Updates/503_outland_auras.sql
http://www.wowhead.com/npc=23067/talonpriest-skizzik
https://web.archive.org/web/20110703070019/http://www.wowhead.com:80/npc=23067#abilities
http://www.wowhead.com/npc=18320/time-lost-shadowmage
https://web.archive.org/web/20110821112220/http://www.wowhead.com:80/npc=18320
> [ACID] Talonpriest Skizzik 23067 

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23264/overmine-flayer
> [ACID] Overmine Flayer 23264

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23326/nethermine-ravager
> [ACID] Nethermine Ravager 23326

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23324/crazed-murkblood-miner
> [ACID] Crazed Murkblood Miner 23324

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23369/whirling-blade
http://www.wowhead.com/npc=22880/shadowmoon-champion
> [ACID] Whirling Blade 23369

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23440/dragonmaw-skybreaker
> [ACID] Dragonmaw Skybreaker 23440

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23441/dragonmaw-skybreaker
> [ACID] Dragonmaw Skybreaker 23441

- ACID/acid_tbc.sql
- Updates/963_c19759_aura.sql
http://www.wowhead.com/spell=12743/immolation#used-by-npc
http://www.wowhead.com/npc=18696/kraator
http://www.wowhead.com/npc=19259/infernal-invader
http://www.wowhead.com/npc=19261/infernal-warbringer
http://www.wowhead.com/npc=19759/newly-crafted-infernal
http://www.wowhead.com/npc=19760/cooling-infernal
http://www.wowhead.com/npc=19973/abyssal-flamebringer
http://www.wowhead.com/npc=21080/dormant-infernal
http://www.wowhead.com/npc=20160/infernal-defender
http://www.wowhead.com/npc=21316/deathforged-infernal
http://www.wowhead.com/npc=23044/karabor-infernal
http://www.wowhead.com/npc=25001/abyssal-flamewalker
> Add Aura for Newly Crafted Infernal 19759

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23161/darkscreecher-akkarai
https://web.archive.org/web/20130602205339/http://www.wowhead.com:80/npc=23161#abilities
* Corrected comments for spell 24240 "Spawn - Red Lightning"
* Missing summoning spell 40426
* Might use spell 38981
> [ACID] Darkscreecher Akkarai 23161

- ACID/acid_tbc.sql
> [ACID] Bone Witch 16380

- ACID/acid_tbc.sql
- Updates/528_c.18235_c.18236.sql
http://www.wowhead.com/npc=18204/ortor-of-murkblood
> [ACID] Ortor of Murkblood 18204

- Updates/1001_taxi_shortcuts_horde_ally_easternkingdoms.sql
Original shortcut data for some Horde and Alliance Eastern Kingdom flight paths as of 2.4.3.
> Next Generation Taxi System for CMaNGOS: taxipack vol.II

- Updates/1002_taxi_shortcuts_alliance_kalimdor.sql
Original shortcut data for major Alliance junction points: Auberdine and Theramore, flight paths as of 2.4.3.
> Next Generation Taxi System for CMaNGOS: taxipack vol.III

- ACID/acid_tbc.sql
- Thuros Lightfingers 61 - http://www.wowhead.com/npc=61/thuros-lightfingers
- Dreamwatcher Forktongue 5348 - http://www.wowhead.com/npc=5348/dreamwatcher-forktongue
- Achellios the Banished 5933 - http://www.wowhead.com/npc=5933/achellios-the-banished
> [WIP][ACID] Bestiary cherry-pick

- ACID/acid_tbc.sql
http://www.wowhead.com/npc=23165/karrog
https://web.archive.org/web/20110821080748/http://www.wowhead.com:80/npc=23165
* Missing spell 40415, probably spell forced target switch
* Might use summoning spells
> [ACID] Karrog 23165

- Updates/0903_Fix_wsg_flag_positions.sql
- Updates/0904_Fix_wsg_flag_positions.sql
> Fix WSG flag positions based on sniffs

- ACID/acid_tbc.sql
based on PR https://github.com/cmangos/tbc-db/pull/803
Broadcast text ID updates in acid.sql file
Content from "0332_creature_ai_texts_broadcast_text_id.sql" file in PR 803 (tbc-db)
File 0332_creature_ai_texts_broadcast_text_id.sql can now be ignored in PR 803 (tbc-db)
> Update some ACID broadcast_text ID

- Updates/0450_maybess_riverbreeze_gossip_improvements.sql
Changed ID to a unique number
Formatted Query in line 6
> fix build error with duplicate gossip id

- Updates/0024_quest_enticing_egolash.sql
Based on https://github.com/vmangos/core/commit/2f041e4024065844afd5ae57c9efbf53f9a5f657
>  Add completion script for Facing Negolash.

- Updates/0023_quest_the_star_the_hand_and_the_heart.sql
Based on https://github.com/vmangos/core/commit/141e7823003aea3fa0c20ae3bdd18762be4b5db5
> Fix spawn script for Dagun the Ravenous.

- Updates/0024_quest_plagued_lands.sql
Based on https://github.com/vmangos/core/commit/e987577c2d22d6fc7d5a3fd6a925a25370b8593c
> Add completion script for quest Plagued Lands.

- Updates/0025_a_gnomes_assistance.sql
Based on https://github.com/vmangos/core/commit/3405d31adcfcd77db68da7ecacb89e6c67395ac5
> Improve completion script for quest A Gnome's Assistance.

- Updates/0036_necklace_recovery.sql
- Updates/0097_necklace_recovery.sql
All timers/coords are based on Sniffs.
Currently NPC Entry: 6868 has SpeedWalk: 1,05 and SpeedRun: 1,14286
May have to update Walk/Run speed too.
`[23] MoverGUID: Full: 0x204600000006B50000008100001D3329 Creature/0 R4480/S129 Map: 0 Entry: 6868 Low: 1913641
[23] WalkSpeed: 2.5
[23] RunSpeed: 8
[23] RunBackSpeed: 4.5
[23] SwimSpeed: 4.72221994400024414
[23] SwimBackSpeed: 2.5
[23] FlightSpeed: 7
[23] FlightBackSpeed: 4.5
[23] TurnRate: 3.141592741012573242
[23] PitchRate: 3.141592741012573242`
> Add quest scripts for "Necklace Recover" quest series

- Updates/0113_npc_tannysa_gossip_text.sql
[Tannysa](https://classic.wowhead.com/npc=5566/tannysa) should say "Another Herbalist, hmm. I doubt your skill is as great as my own so perhaps I can train you in a few proper techniques." if you talk to her while you have Herbalism.
To test:
- .go creature id 5566
- Learn Herbalism from her.
- Talk to her.
Note: I did not test this, because I don't currently have a working TBC client. I just noticed this was missing when I was checking this npc across databases. Classic and WotLK already have it.
> Add gossip text for herbalists for NPC Tannysa

- Updates/0139_quest_noggenfogger.sql
Add completion script for quest "Sprinkles Secret Ingredient"
Add start script for quest "Noggenfogger Elixir"
This closes https://github.com/cmangos/tbc-db/issues/725 and https://github.com/cmangos/tbc-db/issues/726
> Noggenfogger Quest Series

- Updates/0140_quest_the_binding.sql
now is friendly on spawn and gets attackable after 2 seconds.
> Add spawnscript for summoned voidwalker (quest the binding)

- Updates/0217_quest_forsaken_diseases.sql
add quest end script for quest forsaken diseases
rework movement and moveent script for npc 'kayneth stillwind'
all based on tbc ptr sniffs
this closes https://github.com/cmangos/issues/issues/2864
> [Quest] Forsaken Diseases 

- Updates/0277_quest_trial_of_the_lake.sql
https://github.com/cmangos/issues/issues/2912
> [Quest] Trial of the lake - add missing spell event script

- Updates/0261_quest_investigate_the_alchemist_shop.sql
(Horde) and 'Investigate the Blue Recluse' (Alliance)
https://github.com/cmangos/issues/issues/2876
> [Quest] Add start script to quests 'Investigate the Alchemist Shop' 

- Updates/0261_quest_sacred_fire.sql
- Updates/0306_quest_sacred_fire.sql
https://github.com/cmangos/issues/issues/2883
> [Quest] Add endscript for quest 'Alien egg' and 'Sacred Fire'

- Updates/0304_quest_bloodscalp_clan_heads.sql
- Updates/0308_quest_bloodscalp_clan_heads.sql
https://github.com/cmangos/issues/issues/2901
> [Quest] Add endscript for quest 'Bloodscalp Clan Heads'

- Updates/0302_quest_a_little_slime.sql
- Updates/0309_quest_a_little_slime.sql
https://github.com/cmangos/issues/issues/2898
> [Quest] Add endscript for quest 'A Little Slime Goes a Long Way'

- Updates/0305_quest_stormgarde_badges.sql
- Updates/0311_quest_stormgarde_badges.sql
https://github.com/cmangos/issues/issues/2904
> [Quest] Add endscript for quest 'Stromgarde Badges'

- Updates/0307_quest_humble_task.sql
- Updates/0312_quest_humble_task.sql
https://github.com/cmangos/issues/issues/2906
> [Quest] Correct startscript for quest 'A Humble Task'

- Updates/0398_goblin_engineering.sql
- Updates/0410_goblin_engineering.sql
Based on https://tbc.wowhead.com/spell=13240/the-mortar-reloaded
> Add The Mortar: Reloaded to Goblin Engineering Trainer

- Updates/0697_niby_the_almighty_rp.sql
- Updates/0700_niby_the_almighty_rp.sql
Also double checked waypoints from this script, but they are correct. (sniffed wotlk retail)
> [RP] Correct z coordinate in niby the almighty rp script

- Updates/Instances/543_hellfire_ramparts.sql
let adds respawn if player wipes on boss.
add worldstate to prevent boss respawning if he got killed
> [Instance] - Gagolmar - correct spawn coords and update waypoints

- Updates/0010_sw_catherine_vendor.sql
Fixes double selling of some items.
Closes https://github.com/cmangos/issues/issues/3425
> Fix Catherine Leland <Fishing Supplier> Vendor List

- Updates/Instances/540_shattered_halls.sql
add trash between 1st and 2nd boss into spawn_group correct xyz for some mobs
fix assasins - there will come more spawns into this spawn_group in later patch, only added the ones i sniffed so far
next step: gauntlet rework
> [INSTANCE] shattered halls - rework part 2

- Updates/Instances/540_shattered_halls.sql
care: this can broke things but is needed as preperation for next parts
> [INSTANCE] sh - reguid some more npcs

- Updates/0167_shh_callforhelp_radius.sql
- Updates/0207_shh_callforhelp_radius.sql
- Updates/Instances/540_shattered_halls.sql
rewrite the gauntlet of fire event using new systems
> [INSTANCE] shh - rework part 3

- Updates/0210_quest_warn_bolvar.sql
Close https://github.com/cmangos/issues/issues/3100
*TBC only quest
> Add end script for quest 'warn Bolvar!'

- Updates/Instances/540_shattered_halls.sql
this will reduce dberror spam massivly
> [Instance] SHH - rework Legionnaire 2 RP script using stringid

- Updates/Instances/540_shattered_halls.sql
care this will break their respawning, needs a core change for this
> [Instance] add legionnaire 001 group into spawn_group, assign string_id and rewrk rp script

- ACID/acid_tbc.sql
- Updates/0367_shattered_halls_fixes.sql
- Updates/Instances/540_shattered_halls.sql
- utilities/cmangos_custom.sql
add special ai handling for sleeping acolyte and slepping brawlers correct shadowmoon acolyte timers
remove shattered hand legionnaire aura of discipline fix some more CallForHelp based on wotlk classic pulls
add custom UnitFlags to Dummys to fix the bug where shattered hand gladiators and shattered hand centurion attack dummys due to different factions
> [ACID][Instance] shh - fix minor bugs found in latest tests

- Updates/Instances/542_blood_furnace.sql
Put all trash up to first boss into spawn_group
correct waypoints of some trash
> [Instance] Blood Furnance spawn rework part 1

- Updates/0389_dbscript_error_bf.sql
- Updates/Instances/542_blood_furnace.sql
This is the 3rd Part of spawn/grouping rework for blood furnance
there are some open bugs and missing rp parts, this will get added in AI rework
> [Instance] blood furnance rework - part 3

- ACID/acid_tbc.sql
- Updates/0395_bota_spell_list.sql
- Updates/Instances/553_botanica.sql
> [ACID][Instance] The Botanica - rework part 4

- ACID/acid_tbc.sql
- Updates/04345_boss_the_maker.sql
add db changes for this change:
https://github.com/cmangos/mangos-tbc/pull/681
> [ACID] BF: rewrite The Maker into acid and spell_list

- ACID/acid_tbc.sql
- Updates/0459_prospector_anvilward.sql
add prospctor anvilward ooc rp with Ley Keeper Caidanis
> [ACID] rework prospector anvilward gossip

- .github/workflows/build-release.yml
- InstallFullDB.sh
This PR adds bot support to the SQLite daily build.
> Bots: Add SQLite Support

- .github/workflows/build-release.yml
Had a typo in this line, additional space character where it shouldn't go
> CI: Fix typo

- Updates/0477_sethekk_halls_misc_fixes.sql
misspell column name at 0477_sethekk_halls_misc_fixes.sql
> correct column name.

- .github/workflows/build-check.yml
- .github/workflows/build-release.yml
tryfix release build of database
> Git: Update Cache Module to v4, Update MySQL to 8.0.41 (LTS)

- ACID/acid_tbc.sql
- Updates/0557_touch_of_zanzil.sql
- Updates/0560_touch_of_zanzil.sql
Add missing QuestStart and QuestEnd RP 
Add missing GossipMenu when Player lost item
Closes https://github.com/cmangos/issues/issues/3836
> [ACID] SW: Add correct handling for Doc Mixilpixil

- Updates/0577_quest_avruus_orb.sql
Closes https://github.com/cmangos/issues/issues/3895
> Hellfire: Fix Avruu's orb quest based on tbc classic sniffs
