Updates/998_Update_schema.sql

this should take care of the import issue; the import script finishes running now. i set the events with blank times to the new default since i wasn't sure of the dates.
fixes cmangos/tbc-db#25

fix ordering of game_event table updates, add missing backticks

---

ACID/acid_tbc.sql

paired with ported and fixed version of https://github.com/cmangos/mangos-tbc/commit/0597659d0054b6d4fa3e13e56146047338e53170 (only animation is wrong), this will complete the default visual animation for these spawns.
30479 should be cast while in combat on friendlies anyways, with rather short cooldown timer.
Thrash abililty 8876 should probably be moved to creature_template_addon/creature_addon sometime, my personal exp with these passives is that they dont work while being passivly applied to creature_(template)_addon. So i will leave it like this until i have tested the scenario.

[ACID] Move Sleep Aura preventing Spells for 16593 and 16594

---

ACID/acid_tbc.sql

```
('-550','%s goes into a rage after seeing a friend fall in battle!','0','2','0','2287','0'),
('-551','%s calls for help!','0','2','0','Common Emote','0'),
```

Correct Typo for Crushridge Warmonger 2287

---

Updates/326_caverns_of_time.sql

Reverts cmangos/tbc-db#588
518_a_table_and_column_changes does it, which is after migration 326_caverns_of_time.sql

Revert dbscript_string rename change in update file

---

ACID/acid_tbc.sql

http://wowwiki.wikia.com/wiki/Kael%27thas_Sunstrider_(tactics)?oldid=1622799
Has a Multi-Shot attack, drops aggro if any melee or pet attack it. Preferably tanked by a hunter facing it away from the raid to avoid Multi-Shot hitting others. This is the most dangerous weapon and should be killed first by all hunters and ranged DPS which do not take part in the AoE.
* Shoot should prob have Maxrepeat lower as its just cancelled/delayed by multishot, sniffvalues with 15 repetitions had a average repetition of 4secs with mostly 3sec and sometimes 8 when there was a multishot in between.

[ACID] Netherstrand Longbow 21268

---

ACID/acid_tbc.sql

http://www.wowhead.com/npc=22822/ethereum-nullifier
uses 33334 somehow. probably some sort of out of combat rp event

[ACID] Ethereum Nullifier 22822

---

ACID/acid_tbc.sql

http://www.wowhead.com/npc=20394/eye-of-culuthas
https://web.archive.org/web/20111114133627/http://www.wowhead.com:80/npc=20394
Spawns are missing (OOC) Waypoint Script / Aura with http://www.wowhead.com/spell=36296/scan / http://www.wowhead.com/npc=21157/culuthas-scan-target-dummy involved.
Tongue Lash 36398 is not used by this npc, or not anymore

[ACID] Eye of Culuthas 20394

---

Updates/0758_alterac_valley_gate.sql

https://github.com/cmangos/issues/issues/1883
Alterac Valley starting gate is now correctly non-interactable by players, both Horde and Alliance.

Alterac Valley starting gate is now correctly non-interactable.

---

Updates/0064_skyshatter_raiment_spellaffect.sql
Updates/1101_skyshatter_raiment_spellaffect.sql

-Adds correct SpellFamilyMask in spell_affect for 38435. Chainheal familymask is 256. Fixes set bonus for Skyshatter Raiment itemset.
" 38435 - Increases the amount healed by your Chain Heal ability by 5%.

1101_skyshatter_raiment_spellaffect.sql

---

Updates/00022_quest_proof_of_deedsql.sql

https://github.com/cmangos/tbc-db/issues/959
Based on https://github.com/vmangos/core/commit/2df781b127a8dd10ba3e3364371fb9fa786a17b9
I just implemented it like it is in vmangos. But vmangos is missig his normal waypoints. 
(I created a char on retail tbc and can confirm that he has waypoint movement with some small events, just like in cmangos.)
My guess is, that the npc stops his "normal" waypoints and walks straight to the object to do the emote and respawn the object. When finished go back to normal waypoints.
With the current implementation he has 2 more waypoints before going to the object.
(And i also guess, that he removes QuestGiver Flags and adds them after object is spawned. (Thats how TC Wotlk implemented it))
Couldnt find any evidence for this in sniff.
Defnitly need some …

Add completion script for quest Proof of Deed.

---

Updates/0035_summoning_the_princess.sql

Includes https://github.com/cmangos/tbc-db/issues/681
These are the first Quests i started reworked/added scripts based on Video/Sniffs. I didnt want to merge it directly cause i have multiple questions to this.
1. Time Stamps and Delay.
Example
`ServerToClient: SMSG_QUEST_GIVER_QUEST_COMPLETE (0x2A83) Length: 39 ConnIdx: 0 Time: 12/13/2021 18:54:37.079 Number: 21172
ServerToClient: SMSG_UPDATE_OBJECT (0x27C2) Length: 1086 ConnIdx: 1 Time: 12/13/2021 18:54:37.907 Number: 21233
ServerToClient: SMSG_CHAT (0x2BAD) Length: 127 ConnIdx: 0 Time: 12/13/2021 18:54:40.875 Number: 21856
ServerToClient: SMSG_UPDATE_OBJECT (0x27C2) Length: 631 ConnIdx: 1 Time: 12/13/2021 18:54:42.766 Number: 21875
`
These were the events that got used for Quest 652. I used timers 1 second to spawn npc after …

Update quest scripts for 'Summoning the Princess' quest series.

---

Updates/00021_quest_to_server_kumisha.sql
Updates/0138_quest_to_server_kumisha.sql

https://github.com/cmangos/tbc-db/issues/967
Based on https://github.com/vmangos/core/commit/0f8ce721da882766f33e499ae7997f7a10802d1e
This may will need some more updates.
For the last point, i dont wanna change spawn coords with guessed coords. Maybe someone have sniffs/can sniff his exact coords.

Add completion script for quest To Serve Kum'isha.

---

Updates/0298_bg_flag_procs.sql

Ports https://github.com/cmangos/wotlk-db/commit/29154f6be37ce136cd9a69b2e92e9981d2684fe7 to TBC.
Related PR: https://github.com/cmangos/mangos-tbc/pull/546
Co-Authored-By: killerwife <killerwife@users.noreply.github.com>

Make flag BG auras proc from non dmg spells too

---

Updates/Instances/540_shattered_halls.sql

Add trash before last boss into spawn_group
remove assasin's pooling (will work with spawn_group when more spawns got added rework waypoints for assasins
rework Houndmaster + Warhound patrol movement (using spawn_group_formation)
using higher guids for now, because we start at the end of the instance, will reguid and cleanup when rework finished

[INSTANCE] shattered halls rework - part 1

---

ACID/acid_tbc.sql
Updates/0070_kara_moroes_adds.sql

This took me some good time of research.
Here is what i found out from wotlk classic tests/videos and what is different to current implementation with cai.
Baroness Dorothea Millstipe 
- Shadowform only gets Casted inCombat and if not already active (using creature_event_ai - EVENT_T_MISSING_AURA for this but this needs the core change in this pr https://github.com/cmangos/mangos-tbc/pull/614
- Mana Burn seems to have a high CD (using sniffs/ccsdb as evidence for this) (casted on mana users)
Baron Rafe Dreuger
- There is another Seal of Command listed on wowhead/ccsdb not sure if this gets used or is just the proc (id 20424)
Lord Crispin Ference
- Shield Wall only got used when npc was below 20% (using creature_event_ai for this, not repeatable), this could be wrong/wotlk only
- Shield …

[Karazhan] Add Moroes'Guests to spell_list

---

Updates/Instances/429_dire_maul.sql

It should be possible to trap [Guard Slip'kik](https://www.wowhead.com/tbc/npc=14323/guard-slipkik) in Dire Maul North by doing the quest [A Broken Trap](https://www.wowhead.com/tbc/quest=1193/a-broken-trap). 
This is currently not working because the end quest script seems to actually spawn the broken trap again rather than the fixed trap. This PR fixes the script to spawn the correct trap.

DM North: Spawn the correct trap after completing quest 1193.

---

Updates/Instances/230_blackrock_depths.sql

When you start the fight with Ribbly Screwspigot (9543) and his cronies in BRD, they change faction to become hostile and then start to attack players.
But the faction they change to is currently wrong, and they turn hostile for other residents of the bar too, which naturally then start attacking Ribbly and his cronies en mass!
Note: the new faction is coming from version 3.0.3 build 9183 sniffs.

BRD: Fix the faction of Ribbly and his cronies after engaging them.

---

InstallFullDB.sh

Hi! 👋
I was trying to "wrap" the database update process with a script of mine that does some further actions...  
A more complex one to integrate some other stuff...
I found out that the [`InstallFullDB.sh`](https://github.com/cmangos/tbc-db/blob/master/InstallFullDB.sh) partially supports running as a non-interactive script by allowing the user to specify some options...
In particular, one of these options is `-World`.
I've successfully used it to perform the database update process **BUT**...
In some cases, it seems to be not enough to properly start the server as it keeps asking for more updates to be applied.
When it happens, I'm forced to run the `InstallFullDB.sh` interactively and manually select the option #3:  
`Install core updates only`.
With this PR, I want to add to this …

You can now apply the core updates in non-interactive mode.

---

InstallFullDB.sh

I just noticed that -in PR #1112- I forgot to add the help message regarding the added argument.
Sorry... My bad.
This solves this shortcoming.

Add missing description for `-UpdateCore` argument in `show_help` function

---

Updates/0393_paladin_charger_quest_gold.sql

While testing the alliance paladin charger quest chain, I noticed some of the quests that should bring a gold cost were essentially for free. This PR fixes those quests.

Fix the gold requirements of the alliance Paladin charger quest chain.

---

Updates/Instances/429_dire_maul.sql

In Dire Maul West, Illyanna Ravenoak is currently a static spawn, but she should be walking around with her bear Ferra at her side (more or less). This PR adds her waypoints, with data coming from version 3.0.8 build 9506, and puts her in a formation with her bear.
Note: Ferra should be switching sides at the end of the path, but this currently doesn't happen. As far as I could see, it was not possible to do this when I added this, but I've recently seen some core change related to mirroring...

DM West: Illyanna Ravenoak movement.

---

Updates/0541_quest_the_attack.sql
Updates/0542_quest_the_attack.sql

Previously there was a problem with royal guards attacking both Lord Gregor Lescovar and Marzon the Silent Blade making it hard to finish the quest.
Also add correct spawn points/waypoints + intro for Spybot
he spawns a little bit in the back from tyrion and moves to him

Stormwind - add new script for Quest 'The Attack'

---

.github/workflows/build-release.yml

This PR fixes the empty date value for release builds. Issue was caused because of using bash syntax instead of powershell.

GitHub: Fix date output for release builds
